---
title: "Income and poverty mapping"
author: "Rebecca Witinok-Huber"
date: "12/7/2020"
output: html_document
---

```{r setup, include=FALSE}
knitr::opts_chunk$set(echo = FALSE, message = FALSE, warning = FALSE, CB = FALSE)
```


```{r load_data}
library(tidyverse)
library(ggplot2)
library(tigris)
library(na.tools)
library(lubridate)
library(leaflet)
library(ggrepel)
library(viridis)
library(plotly)

#state_policy <- read_csv("raw_data/state_policy_updates_20201122_0721.csv")
LC_covid <- read_csv("raw_data/LC-COVID-casesdata.csv")
covid_deaths <- read_csv("raw_data/covid_deaths.csv")
income <- read_csv("raw_data/Income_Poverty__Census_Tracts_.csv")

### Pull census data for Larimer county 

larimer_tracts <- tracts(state = 08, county =069, 
                        cb = TRUE, class = "sf")
```


```{r data_manipulation}
### Filter the income data to just Larimer county

larimer_income <- income %>%
  filter(County == "LARIMER")

### Join the data sets 

larimer_info <- full_join(larimer_income, larimer_tracts, 
                          by = list(x = "FIPS", y = "GEOID"))

### Make all city names in title format to join data sets

LC_covid <- LC_covid %>% 
  mutate(City = str_to_title(City))

### Create vectors of gps coordinates of cities from information collected from
### the internet

Lat <- c(40.625679, 40.284667, 38.894137, 40.431269, 40.377117, 40.559167, 
         40.453740, 40.336944, 40.633808, 40.794319, 40.404789, 40.487171,
         40.807820, 40.529718, 40.702324, 40.477222)

Lon <- c( -105.171089, -104.965504, -107.925498, -105.339661, -105.525514,
          -105.078056, -105.448837, -104.912222, -105.148819, -105.216579,
          -105.085868, -105.210056,-105.578641, -104.981654, 
          -105.005497, -104.911944)

City <- c("Bellvue", "Berthoud", "Cedaredge", "Drake", "Estes Park",
          "Fort Collins", "Glen Haven", "Johnstown", "Laporte", "Livermore",
          "Loveland", "Masonville", "Red Feather Lakes", "Timnath", 
          "Wellington", "Windsor")

### Combine the vectors into a data frame and then join the data sets so cities
### have coordinates associated with them for mapping and remove NA values

larimer_gps <- data.frame(City, Lat, Lon)

LC_covid_gps <- full_join(larimer_gps, LC_covid, by = "City") %>% 
  na.rm()

LC_covid_gps <- LC_covid_gps %>% 
  mutate(ReportedDate = mdy(ReportedDate)) 

LC_covid_gps <- LC_covid_gps %>% 
  mutate(month = month(ReportedDate, label = TRUE,
                     abbr = FALSE),
       weekday = wday(ReportedDate, label = TRUE,
                      abbr = FALSE)) %>% 
  mutate(popup_info = paste("<b>Location:</b>", City, "<br/>",
                            "<b>Age:</b>", Age, "<br/>",
                            "<b>Date:</b>", ReportedDate, "<br/>",
                            "<b>Total # of cases:</b>", CaseCount))

total_covid_per_city <- LC_covid %>% 
  group_by(City) %>% 
  count()

total_covid <- full_join(total_covid_per_city, larimer_gps, by = "City") %>% 
  na.rm()
```


```{r covid_coords}
### Provide covid deaths with coordinates

covid_deaths <- full_join(larimer_gps, covid_deaths, 
                          by = list(x = "City", y = "city")) %>% 
  na.rm()

mean_age_deaths <- covid_deaths %>% 
  group_by(City) %>% 
  summarize(mean_age = mean(age), .groups = "drop")

mean_age_deaths <- full_join(larimer_gps, mean_age_deaths, by = "City") %>% 
  na.rm() %>% 
  mutate(popup_info = paste("<b>Location:</b>", City, "<br/>",
                            "<b>Mean age of death:</b>", mean_age))
```


```{r keyvars_income}

#Creating a new dataset with fewer variables
larimer_short <- larimer_info %>%
  select(Population_Total:Poverty_Per_Capita_Income, TRACTCE)

#Join income vars with larimer_tracts by "TRACTCE", now income vars have coords
tracts_income <- larimer_tracts %>% left_join(.,larimer_short, by = "TRACTCE") 
```


* This is where I'll need to do something to combine lat/lon in covid with 
  geometry in tracts
  
```{r newdf-covid}
#How to join LC_covid_gps with to larimer_tracts with no common col?
# larimer_tracts <- LC_covid_gps %>%
#   select(City:weekday, )
```


## Income-Poverty Maps

* maps created 1-by-1 ----

```{r maps}
#side by side plots
par(mfrow=c(2,2))

#figure for larimer county population totals
#larimer_tracts %>% left_join(.,larimer_short, by = "TRACTCE") #use tracts_income
  
  
  tracts_income %>%
  ggplot() +
  geom_sf(aes(fill = Population_Total)) +
  geom_point(data = larimer_gps %>%
               filter(City!="Cedaredge"), aes(x=Lon, y=Lat)) +
               geom_text_repel(data = larimer_gps %>%
                        filter(City!="Cedaredge"), 
                        aes(x=Lon, y=Lat, 
                        label = City), color = "black",
                        show.legend=NA, 
                        nudge_x = .1, nudge_y = .1) +
  scale_fill_viridis(name = "City Population", direction = -1, option = "cividis") +
  ggtitle("Population Totals for Cities in Larimer County") 

#Figure for income
tracts_income %>%
  ggplot() +
  geom_sf(aes(fill = Poverty_Mean_Household_Income)) +
  geom_point(data = larimer_gps %>%
               filter(City!="Cedaredge"), aes(x=Lon, y=Lat)) +
               geom_text_repel(data = larimer_gps %>%
                        filter(City!="Cedaredge"), 
                        aes(x=Lon, y=Lat, 
                        label = City), color = "black",
                        show.legend=NA, 
                        nudge_x = .1, nudge_y = .1) +
  ggtitle("Mean Income for Larimer County") +
  scale_fill_viridis(name = "Income (USD)", direction = -1, option = "cividis")

#Figure for pov per capita income
tracts_income %>%
  ggplot() +
  geom_sf(aes(fill = Poverty_Per_Capita_Income)) +
  geom_point(data = larimer_gps %>%
               filter(City!="Cedaredge"), aes(x=Lon, y=Lat)) +
               geom_text_repel(data = larimer_gps %>%
                        filter(City!="Cedaredge"), 
                        aes(x=Lon, y=Lat, 
                        label = City), color = "black",
                        show.legend=NA, 
                        nudge_x = .1, nudge_y = .1) +
  ggtitle("Poverty Per Capita Income for Larimer County") +
  scale_fill_viridis(name = "Number of People", direction = -1, option = "cividis")

#Percent of population below poverty levels
tracts_income %>%
  ggplot() +
  geom_sf(aes(fill = Percent_Poverty_AllPeople_Income_Below_Pov_Level)) +
  geom_point(data = larimer_gps %>%
               filter(City!="Cedaredge"), aes(x=Lon, y=Lat)) +
               geom_text_repel(data = larimer_gps %>%
                        filter(City!="Cedaredge"), 
                        aes(x=Lon, y=Lat, 
                        label = City), color = "black",
                        show.legend=NA, 
                        nudge_x = .1, nudge_y = .1) +
  ggtitle("Percent of Larimer County Below the Poverty Level") +
  scale_fill_viridis(name = "Percent", direction = -1, option = "cividis")
```


*trying to create income maps side-by-side using pivot_longer and facet_wrap*
  
```{r pivotlong}

#Pivot df with geodata and income vars longer, names=income vars and thier values
income_long <- pivot_longer(tracts_income,
    cols = Population_Total:Poverty_Per_Capita_Income)
head(income_long)
```


```{r smallmultiples}

#create factor levels from col = name for each income var
name_levels <-
  factor(income_long$name, 
         levels = c("Population_Total",
                    "Population_Density_PerLandSquareMile",
                    "Percent_Poverty_AllPeople_Income_Below_Pov_Level",
                    "Poverty_Median_Household_Income",
                    "Poverty_Mean_Household_Income",
                    "Poverty_Per_Capita_Income"))
#plot 

tracts_income %>%
  ggplot() +
  geom_sf(aes(fill = Percent_Poverty_AllPeople_Income_Below_Pov_Level)) +
  geom_point(data = larimer_gps %>%
               filter(City!="Cedaredge"), aes(x=Lon, y=Lat)) +
               geom_text_repel(data = larimer_gps %>%
                        filter(City!="Cedaredge"), 
                        aes(x=Lon, y=Lat, 
                        label = City), color = "black",
                        show.legend=NA, 
                        nudge_x = .1, nudge_y = .1) +
  ggtitle("Percent of Larimer County Below the Poverty Level") +
  scale_fill_viridis(name = "Percent", direction = -1, option = "cividis")
ggplot(income_long, aes(x=))

class()

income_long %>%
  ggplot() +
  geom_sf(aes(fill = name)) +
  geom_point(data = larimer_gps %>%
               filter(City!="Cedaredge"), aes(x=Lon, y=Lat)) +
               geom_text_repel(data = larimer_gps %>%
                        filter(City!="Cedaredge"),
                        aes(x=Lon, y=Lat,
                        label = City), color = "black",
                        show.legend=NA,
                        nudge_x = .1, nudge_y = .1) +
      scale_fill_viridis(name = "City Population", direction = -1,
      option = "cividis") +
       facet_wrap(~name) 
  

tracts_income_long <- income_long %>%
  select(geometry:value)


# ggplotly(plot)
```

```{r}
larimer_gps %>%
  ggplot() +
   geom_point(data = larimer_gps %>%
               filter(City!="Cedaredge"), aes(x=Lon, y=Lat)) +
               geom_text_repel(data = larimer_gps %>%
                        filter(City!="Cedaredge"), 
                        aes(x=Lon, y=Lat, 
                        label = City), color = "black",
                        show.legend=NA, 
                        nudge_x = .1, nudge_y = .1)
```

