---
title: "timeline covid cases - larimer county"
author: "Kailee Reed"
date: "12/7/2020"
output: html_document
---

```{r setup, include=FALSE}
knitr::opts_chunk$set(echo = FALSE, message = FALSE, warning = FALSE)
```

```{r setup, load_data}

# Load libraries needed for analysis
library(tidyverse)
library(magrittr)
library(ggplot2)
library(ggthemes)
library(dplyr)
library(lubridate)

#Load dataset 
lc_covid <- read.csv("raw_data/LC-COVID-casesdata.csv")
```

```{r setup, manipulate_data}

# Group by reported date (combining to make total COVID cases)
total_covid <- lc_covid %>%
  group_by(ReportedDate) %>%
  count()

# Check the class before mutating 
class(x = total_covid$ReportedDate)

# Mutate to mdy 
total_covid <- mutate(.data = total_covid, 
                      date = mdy(ReportedDate))

# Group by month 
month_covid <- total_covid %>%
  group_by(month = floor_date(date, "month")) %>%
  summarise(n=sum(n))

```

```{r setup, graph_data}

# Plot date and totals with line graph
total_covid %>%
  ggplot() + 
  geom_line(aes(x = date, y = n)) + 
  theme_stata() + 
  ggtitle("Total COVID Cases in Larimer County from March to December") + 
  xlab("Date of Confirmed Cases (March-December)") + 
  ylab("Total COVID Cases")

```







